services:
  api:
    build: ./api
    container_name: compose-hands-on-you-do-advanced-api
    ports:
      - 8888:8080
    volumes:
      - ./api:/app
    networks:
      - happy-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: compose-hands-on-you-do-advanced-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=appdb
    networks:
      - happy-network
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: psql -U postgres
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s



networks:
  happy-network:
    driver: bridge