services:
  api:
    build:
      target: development
    container_name: compose-hands-on-you-do-api
    command: java -jar api.jar

  db:
    image: postgres:15
    container_name: compose-hands-on-you-do-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=appdb
    depends_on:
      - api
