FROM gradle:8 AS base
CMD ["bash"]


FROM base AS server_build
WORKDIR /api
COPY ../api .
RUN ./gradlew build --no-daemon -x test


FROM openjdk:21 AS development
EXPOSE 7070
COPY --from=server_build /api/build/libs/api-0.0.1-SNAPSHOT.jar ./app.jar
