services:
  api:
    build:
      dockerfile: ./docker/Dockerfile
      target: development
    container_name: api-container
    ports:
      - 8888:8080
    command: java -jar app.jar
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=appdb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: